### PR TITLE
Bin2 dec

### PR DESCRIPTION
**Pull request by Brymmobaggins**
# Pull Request

## Description (required)

A clear and concise description of what your calculator does or the problem/improvement it is solving.

## Checklist (required)

- [x] I have read and understand the contribution guidelines.
- [x] I have tested this code.
- [x] I have updated the documentation.
- [x] I followed the standards described in the README.
- [x] I have reviewed and addressed any comments and feedback.

## Screenshots (optional)

If applicable, add screenshots that help visualize the changes you made.

## Related Issues (required)

Issue: #62

### CODE REVIEW

**Comment by RuanAragao** [comment]
You need read the items of the **Checklist** and check as you confirm. 
Exemple:
```mardown
- [ ]  I have read and understand the contribution guidelines.
```

if you did what is written in the item. Mark with an X, as in the following example:

```mardown
- [x]  I have read and understand the contribution guidelines.
```

**Comment by Brymmobaggins** [comment]
checked

**Comment by RuanAragao** [comment]
Does your PR have two calculators? There must be only one per PR.

If you need to correct something in a calculator that is already in the project, open an issue stating what you will do.

Any doubt I am available.

**Comment by Brymmobaggins** [comment]
I had one calculator per PR 

My first PR was PX to EM converter #70 which has been merged.

The present PR is Binary to decimal converter #81 awaiting to be merged

**Comment by RuanAragao** [comment]
> I had one calculator per PR
> 
> My first PR was PX to EM converter #70 which has been merged.
> 
> The present PR is Binary to decimal converter #81 awaiting to be merged

See files in the top menu, both calculators are present in this PR.

https://github.com/RuanAragao/calculator/pull/81/files

**Pull request closed without merging**
