### PR TITLE
General Purpose Calculator

### LINKED ISSUE #20: General Purpose Calculator
This calculator has basic functionalities and can be handful.
Has good design and is gets its job done.

### PR DESCRIPTION
**Pull request by TIDYMOUSE**
Closes #20

### CODE REVIEW

**Comment by TIDYMOUSE** [comment]
@RuanAragao Hello, this is one of my earliest basic js project, would be great if you can review it

**Comment by RuanAragao** [comment]
> @RuanAragao Hello, this is one of my earliest basic js project, would be great if you can review it

No problem. Follow the changes I commented. If you have any questions, I'm here to help.

**Comment by TIDYMOUSE** [comment]
Thank You for responding @RuanAragao . May I know where have you commented the changes you require?

**Comment by RuanAragao** [comment]
> Thank You for responding @RuanAragao . May I know where have you commented the changes you require?

In the header of this section, there is a navigation bar, the last item is ("Files change")[https://github.com/RuanAragao/calculator/pull/24/files]. You can see the comments in the code.

You can see here above, there is an automatic comment from me: "RuanAragao started a review"

**Review by TIDYMOUSE — COMMENTED** [review]
code reviewed

**Comment by TIDYMOUSE** [comment]
Hello, @RuanAragao

**Comment by TIDYMOUSE** [comment]
Hello, @RuanAragao I cannot see any reviews/changes asked by you. Also you havent assigned yourself as a reviewer and me as an assignee.

**Comment by RuanAragao** [comment]
@TIDYMOUSE 
1. The main file in the calculator folder needs to be called "index.html".
2. Review the general index.html, it has a repeated link.

**Comment by TIDYMOUSE** [comment]
@RuanAragao I have made the requested changes

**Comment by TIDYMOUSE** [comment]
@RuanAragao please respond

**Comment by RuanAragao** [comment]
@TIDYMOUSE The link is still broken `<a href="./calculators/general-purpose-calculator/cal.html"`

**Comment by TIDYMOUSE** [comment]
done @RuanAragao

**Review by RuanAragao — APPROVED** [review]

**Pull request merged**
