### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by ayushsgit**
# Pull Request

## Description (required)
Index UI Update

## Checklist (required)

- [x] I have read and understand the contribution guidelines.
- [x] I have tested this code.
- [x] I have updated the documentation.
- [x] I followed the standards described in the README.
- [x] I have reviewed and addressed any comments and feedback.

## Screenshots (optional)

If applicable, add screenshots that help visualize the changes you made.

## Related Issues (required)

Issue: #34 [Link to any related issues or tasks.]

### CODE REVIEW

**Review by RuanAragao — APPROVED** [review]

**Comment by ayushsgit** [comment]
@RuanAragao Hey you can merge this now
before more conflicts arises

**Review by RuanAragao — CHANGES_REQUESTED** [review]
@ayushsgit I believe your code is not as you would like. Please always review all your code and test it to make sure it is as expected before opening any PR. Quality and consistency will always be expected of you as a professional, regardless of the size of the project, or whether it is private or OpenSource.
image

**Comment by ayushsgit** [comment]
I have a question
Like i changes index.html and its working fine
but their are files in their are 4 new calculators added
i added them in index.html file but now in files folder of calculator
do i have to add them to in my PR?
https://calm-faun-0f771e.netlify.app/

**Comment by ayushsgit** [comment]
@RuanAragao Can you Please check

**Pull request closed without merging**
