### PR TITLE
Added Investment calculator correctly #43

### PR DESCRIPTION
**Pull request by Dhandeep10**
# Pull Request

## Description (required)

A clear and concise description of what your calculator does or the problem/improvement it is solving.

## Checklist (required)

- [x] I have read and understand the contribution guidelines.
- [x] I have tested this code.
- [x] I have updated the documentation.
- [x] I followed the standards described in the README.
- [x] I have reviewed and addressed any comments and feedback.

## Screenshots (optional)

If applicable, add screenshots that help visualize the changes you made.

## Related Issues (required)

Issue: #XXX [Link to any related issues or tasks.]

### CODE REVIEW

**Review by RuanAragao — CHANGES_REQUESTED** [review]
Please fill out the pull request template correctly.

**Comment by Dhandeep10** [comment]
@RuanAragao 
corrected the pr template

**Comment by Dhandeep10** [comment]
@RuanAragao 
Corrected the code for index.html
please review it and merge this

**Comment by Dhandeep10** [comment]
@RuanAragao 
please review it

**Review by RuanAragao — APPROVED** [review]

**Pull request merged**
