### PR TITLE
Temperature Calculator Ready

### LINKED ISSUE #51: Temperature Calculator Not Working
- Temperature calculator not working as expected.
- UI/UX is not very good.

image

- Adding the functioning and removing the errors.
- Make an attractive UI/ UX for the temperature calculator.
- Hover effect and fluid effect on the button.
- Good font style and font size.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Closes #51 

image

- Attractive user interface.
- Perfect functioning.
- Quick responsive and best user experience.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@RuanAragao please review this pull request and requested to merge it under hacktoberfest 2023

**Review by RuanAragao — CHANGES_REQUESTED** [review]
You need to add the link to your calculator in the project's main index.html.

Read README: https://github.com/RuanAragao/calculator#how

**Comment by Avdhesh-Varshney** [comment]
@RuanAragao this is just a enhancement not a new calculator. So, `index.html` file is already attached to the main `index.html` file.

**Review by RuanAragao — APPROVED** [review]

**Comment by RuanAragao** [comment]
> @RuanAragao this is just a enhancement not a new calculator. So, `index.html` file is already attached to the main `index.html` file.

My apologies, it's true. Thanks for the contribution!

**Pull request merged**
